/* Allegro datafile object indexes, produced by grabber v3.0 + WIP */
/* Datafile: d:\c\ddd.dat */
/* Date: Sun Jul  4 18:37:33 1999 */
/* Do not hand edit! */

#define FONT_1                           0        /* FONT */
#define GUY                              1        /* BMP  */
#define HIDE                             2        /* BMP  */
#define MIDI001                          3        /* MIDI */
#define MON                              4        /* BMP  */
#define PALLETE_01                       5        /* PAL  */
#define SAMP001                          6        /* SAMP */
#define SAMP002                          7        /* SAMP */
#define WALL000                          8        /* BMP  */
#define WALL001                          9        /* BMP  */
#define WALL002                          10       /* BMP  */
#define WALL003                          11       /* BMP  */
#define WALL004                          12       /* BMP  */
#define WALL005                          13       /* BMP  */
#define WALL006                          14       /* BMP  */
#define WALL007                          15       /* BMP  */
#define WALL008                          16       /* BMP  */
#define WALL009                          17       /* BMP  */
#define WALL010                          18       /* BMP  */
#define WALL011                          19       /* BMP  */
#define WALL012                          20       /* BMP  */
#define WALL013                          21       /* BMP  */
#define WALL014                          22       /* BMP  */
#define WALL015                          23       /* BMP  */
#define WALL016                          24       /* BMP  */
#define WALL017                          25       /* BMP  */
#define WALL018                          26       /* BMP  */
#define WALL019                          27       /* BMP  */
#define WALL020                          28       /* BMP  */
#define WALL021                          29       /* BMP  */
#define WALL022                          30       /* BMP  */
#define WALL023                          31       /* BMP  */
#define WALL024                          32       /* BMP  */
#define WALL025                          33       /* BMP  */
#define WALL026                          34       /* BMP  */
#define WALL027                          35       /* BMP  */
#define WALL028                          36       /* BMP  */
#define WALL029                          37       /* BMP  */
#define WALL030                          38       /* BMP  */
#define WALL031                          39       /* BMP  */
#define WALL032                          40       /* BMP  */
#define WALL033                          41       /* BMP  */
#define WALL034                          42       /* BMP  */
#define WALL035                          43       /* BMP  */
#define WALL036                          44       /* BMP  */
#define WALL037                          45       /* BMP  */
#define WALL038                          46       /* BMP  */
#define WALL039                          47       /* BMP  */
#define WALL040                          48       /* BMP  */
#define WALL041                          49       /* BMP  */
#define WALL042                          50       /* BMP  */
#define WALL043                          51       /* BMP  */
#define WALL044                          52       /* BMP  */
#define WALL045                          53       /* BMP  */
#define WALL046                          54       /* BMP  */
#define WALL047                          55       /* BMP  */
#define WALL048                          56       /* BMP  */
#define WALL049                          57       /* BMP  */
#define WALL050                          58       /* BMP  */
#define WALL051                          59       /* BMP  */
#define WALL052                          60       /* BMP  */
#define WALL053                          61       /* BMP  */
#define WALL054                          62       /* BMP  */
#define WALL055                          63       /* BMP  */
#define WALL056                          64       /* BMP  */
#define WALL057                          65       /* BMP  */
#define WALL058                          66       /* BMP  */
#define WALL059                          67       /* BMP  */
#define WALL060                          68       /* BMP  */
#define WALL061                          69       /* BMP  */
#define WALL062                          70       /* BMP  */
#define WALL063                          71       /* BMP  */
#define WALL064                          72       /* BMP  */
#define WALL065                          73       /* BMP  */
#define WALL066                          74       /* BMP  */
#define WALL067                          75       /* BMP  */
#define WALL068                          76       /* BMP  */
#define WALL069                          77       /* BMP  */
#define WALL070                          78       /* BMP  */
#define WALL071                          79       /* BMP  */
#define WALL072                          80       /* BMP  */
#define WALL073                          81       /* BMP  */
#define WLADDER                          82       /* BMP  */
#define WOBJECT001                       83       /* BMP  */
#define WOBJECT002                       84       /* BMP  */
#define WOBJECT003                       85       /* BMP  */
#define WOBJECT004                       86       /* BMP  */
#define ZMON01                           87       /* BMP  */
#define ZMON02                           88       /* BMP  */
#define ZMON03                           89       /* BMP  */

