/* Allegro datafile object indexes, produced by grabber v3.0 + WIP */
/* Datafile: d:\c\guy.dat */
/* Date: Sun Jul  4 18:25:53 1999 */
/* Do not hand edit! */

#define ELEV01                           0        /* BMP  */
#define GUY01                            1        /* BMP  */
#define GUY02                            2        /* BMP  */
#define GUY03                            3        /* BMP  */
#define GUY04                            4        /* BMP  */
#define GUY05                            5        /* BMP  */
#define GUY06                            6        /* BMP  */
#define GUY07                            7        /* BMP  */
#define GUY08                            8        /* BMP  */
#define GUY09                            9        /* BMP  */
#define GUY10                            10       /* BMP  */
#define GUY11                            11       /* BMP  */
#define GUY12                            12       /* BMP  */
#define GUY13                            13       /* BMP  */
#define GUY14                            14       /* BMP  */
#define GUY15                            15       /* BMP  */
#define GUY16                            16       /* BMP  */
#define MON01                            17       /* BMP  */
#define MON02                            18       /* BMP  */
#define OGUY01                           19       /* BMP  */
#define OGUY02                           20       /* BMP  */
#define OGUY03                           21       /* BMP  */
#define OGUY04                           22       /* BMP  */
#define OGUY05                           23       /* BMP  */
#define OGUY06                           24       /* BMP  */
#define OGUY07                           25       /* BMP  */
#define OGUY08                           26       /* BMP  */
#define OGUY09                           27       /* BMP  */
#define OGUY10                           28       /* BMP  */
#define OGUY11                           29       /* BMP  */
#define OGUY12                           30       /* BMP  */
#define OGUY13                           31       /* BMP  */
#define OGUY14                           32       /* BMP  */
#define OGUY15                           33       /* BMP  */
#define OGUY16                           34       /* BMP  */

