/* Allegro datafile object indexes, produced by grabber v4.0.3, MSVC */
/* Datafile: f:\software\CDsrc\run\data\scorch.dat */
/* Date: Wed May 23 19:01:33 2007 */
/* Do not hand edit! */

#define AI_PROFILE                       0        /* BMP  */
#define AITANK_PROFILE                   1        /* BMP  */
#define APRIL_CHART                      2        /* BMP  */
#define APRIL_ICON                       3        /* BMP  */
#define APRIL_PROFILE                    4        /* BMP  */
#define ARIAL                            5        /* FONT */
#define BHBOMB_BACKGROUND                6        /* BMP  */
#define BLANK_PROFILE                    7        /* BMP  */
#define BUTTON_MAIN                      8        /* BMP  */
#define BUTTON_MAINDOWN                  9        /* BMP  */
#define BUYSTUFF_BACKGROUND              10       /* BMP  */
#define BUYSTUFF_DEFENSE_DOWN            11       /* BMP  */
#define BUYSTUFF_DEFENSE_OVER            12       /* BMP  */
#define BUYSTUFF_DEFENSE_UP              13       /* BMP  */
#define BUYSTUFF_DONE_DOWN               14       /* BMP  */
#define BUYSTUFF_DONE_OVER               15       /* BMP  */
#define BUYSTUFF_DONE_UP                 16       /* BMP  */
#define BUYSTUFF_ICON_AI                 17       /* BMP  */
#define BUYSTUFF_ICON_BALLISTIC          18       /* BMP  */
#define BUYSTUFF_ICON_CONVENTIONAL       19       /* BMP  */
#define BUYSTUFF_ICON_ENERGY             20       /* BMP  */
#define BUYSTUFF_ICON_HEAT               21       /* BMP  */
#define BUYSTUFF_ICON_LIQUID             22       /* BMP  */
#define BUYSTUFF_ICON_SHOOTAGAIN         23       /* BMP  */
#define BUYSTUFF_ICON_SUPERBALLISTIC     24       /* BMP  */
#define BUYSTUFF_ICON_SUPERCONVENTIONAL  25       /* BMP  */
#define BUYSTUFF_ICON_SUPERENERGY        26       /* BMP  */
#define BUYSTUFF_ICON_SUPERHEAT          27       /* BMP  */
#define BUYSTUFF_SELL_DOWN               28       /* BMP  */
#define BUYSTUFF_SELL_OVER               29       /* BMP  */
#define BUYSTUFF_SELL_UP                 30       /* BMP  */
#define BUYSTUFF_SPECIAL_DOWN            31       /* BMP  */
#define BUYSTUFF_SPECIAL_OVER            32       /* BMP  */
#define BUYSTUFF_SPECIAL_UP              33       /* BMP  */
#define BUYSTUFF_WEAPONS_DOWN            34       /* BMP  */
#define BUYSTUFF_WEAPONS_OVER            35       /* BMP  */
#define BUYSTUFF_WEAPONS_UP              36       /* BMP  */
#define CHALLENGER                       37       /* BMP  */
#define COMIC                            38       /* FONT */
#define COMIC_FONT_PAL                   39       /* PAL  */
#define CONGRADULATIONS                  40       /* BMP  */
#define GROUND_BURN                      41       /* BMP  */
#define GUNNER_ICON                      42       /* BMP  */
#define HUD_TOPLEFT                      43       /* BMP  */
#define HUD_TOPLEFT_COLOR                44       /* BMP  */
#define HUD_TOPRIGHT                     45       /* BMP  */
#define HUD_TOPRIGHTBLACK                46       /* BMP  */
#define INTERMISSION_BACK                47       /* BMP  */
#define JACK_CHART                       48       /* BMP  */
#define JACK_ICON                        49       /* BMP  */
#define JACK_PROFILE                     50       /* BMP  */
#define JIRA_CHART                       51       /* BMP  */
#define JIRA_ICON                        52       /* BMP  */
#define JIRA_PROFILE                     53       /* BMP  */
#define JIRA_SECRET                      54       /* BMP  */
#define LCD                              55       /* FONT */
#define LOBBER_ICON                      56       /* BMP  */
#define LOCK_CHART                       57       /* BMP  */
#define LOCK_ICON                        58       /* BMP  */
#define LOCK_PROFILE                     59       /* BMP  */
#define MENU_SHADER                      60       /* BMP  */
#define MESHKO_CHART                     61       /* BMP  */
#define MESHKO_ICON                      62       /* BMP  */
#define MESHKO_PROFILE                   63       /* BMP  */
#define MIA_CHART                        64       /* BMP  */
#define MIA_ICON                         65       /* BMP  */
#define MIA_PROFILE                      66       /* BMP  */
#define MIKI_CHART                       67       /* BMP  */
#define MIKI_ICON                        68       /* BMP  */
#define MIKI_PROFILE                     69       /* BMP  */
#define MOUSE_CURSOR                     70       /* BMP  */
#define MS                               71       /* FONT */
#define PLAYERSETUP_BACKGROUND           72       /* BMP  */
#define PLAYERSETUP_CHOOSECHAR           73       /* BMP  */
#define PLAYERSETUP_NEXT                 74       /* BMP  */
#define PLAYERSETUP_NEXTOVER             75       /* BMP  */
#define PLAYERSETUP_PLATE                76       /* BMP  */
#define QUESTION_ICON                    77       /* BMP  */
#define QUESTION_PROFILE                 78       /* BMP  */
#define REALTIMEHEB                      79       /* BMP  */
#define RICHIE_CHART                     80       /* BMP  */
#define RICHIE_ICON                      81       /* BMP  */
#define RICHIE_PROFILE                   82       /* BMP  */
#define RICHIE_SECRET                    83       /* BMP  */
#define SARU_CHART                       84       /* BMP  */
#define SARU_ICON                        85       /* BMP  */
#define SARU_PROFILE                     86       /* BMP  */
#define SHADOWFANG_CHART                 87       /* BMP  */
#define SHADOWFANG_ICON                  88       /* BMP  */
#define SHADOWFANG_PROFILE               89       /* BMP  */
#define SHADOWFANG_SECRET                90       /* BMP  */
#define SHOOTER_ICON                     91       /* BMP  */
#define SL_BACKGROUND                    92       /* BMP  */
#define SL_FOREGROUND1                   93       /* BMP  */
#define SL_FOREGROUND2                   94       /* BMP  */
#define SL_FOREGROUND3                   95       /* BMP  */
#define SL_FOREGROUND4                   96       /* BMP  */
#define SMACKBRINGER_CHART               97       /* BMP  */
#define SMACKBRINGER_ICON                98       /* BMP  */
#define SMACKBRINGER_PROFILE             99       /* BMP  */
#define SMACKBRINGER_SECRET              100      /* BMP  */
#define SNIPER_ICON                      101      /* BMP  */
#define SNOOT10                          102      /* FONT */
#define STACIERICKY_CHART                103      /* BMP  */
#define STACIERICKY_ICON                 104      /* BMP  */
#define STACIERICKY_PROFILE              105      /* BMP  */
#define STATUS_LEFT                      106      /* BMP  */
#define STATUS_MID                       107      /* BMP  */
#define STATUS_RIGHT                     108      /* BMP  */
#define STOOPID_ICON                     109      /* BMP  */
#define TAHOMA                           110      /* FONT */
#define TAHOMA10                         111      /* FONT */
#define TANK10_INGAME                    112      /* BMP  */
#define TANK10_PROFILE                   113      /* BMP  */
#define TANK11_INGAME                    114      /* BMP  */
#define TANK11_PROFILE                   115      /* BMP  */
#define TANK12_INGAME                    116      /* BMP  */
#define TANK12_PROFILE                   117      /* BMP  */
#define TANK1_INGAME                     118      /* BMP  */
#define TANK1_PROFILE                    119      /* BMP  */
#define TANK2_INGAME                     120      /* BMP  */
#define TANK2_PROFILE                    121      /* BMP  */
#define TANK3_INGAME                     122      /* BMP  */
#define TANK3_PROFILE                    123      /* BMP  */
#define TANK4_INGAME                     124      /* BMP  */
#define TANK4_PROFILE                    125      /* BMP  */
#define TANK5_INGAME                     126      /* BMP  */
#define TANK5_PROFILE                    127      /* BMP  */
#define TANK6_INGAME                     128      /* BMP  */
#define TANK6_PROFILE                    129      /* BMP  */
#define TANK7_INGAME                     130      /* BMP  */
#define TANK7_PROFILE                    131      /* BMP  */
#define TANK8_INGAME                     132      /* BMP  */
#define TANK8_PROFILE                    133      /* BMP  */
#define TANK9_INGAME                     134      /* BMP  */
#define TANK9_PROFILE                    135      /* BMP  */
#define TANK_FLOATATION                  136      /* BMP  */
#define TANK_PARACHUTE                   137      /* BMP  */
#define TANK_SHADOW                      138      /* BMP  */
#define TANKai1_INGAME                   139      /* BMP  */
#define TANKai2_INGAME                   140      /* BMP  */
#define TANKai3_INGAME                   141      /* BMP  */
#define TANKai4_INGAME                   142      /* BMP  */
#define TANKai5_INGAME                   143      /* BMP  */
#define TANKai6_INGAME                   144      /* BMP  */
#define TEST_TANK                        145      /* BMP  */
#define TINY8                            146      /* FONT */
#define TITLESCREEN                      147      /* BMP  */
#define TITLESCREEN_BMMG                 148      /* BMP  */
#define UNKNOWN_CHART                    149      /* BMP  */
#define UNKNOWN_PROFILE1                 150      /* BMP  */
#define UNKNOWN_PROFILE2                 151      /* BMP  */
#define UNKNOWN_PROFILE3                 152      /* BMP  */
#define UNLIMITED_ICON                   153      /* BMP  */
#define VER10                            154      /* FONT */

