/* Allegro datafile object indexes, produced by grabber v4.0.3, MSVC */
/* Datafile: f:\software\CDsrc\run\data\sounds.dat */
/* Date: Wed May 23 19:07:13 2007 */
/* Do not hand edit! */

#define AIRSHIP                          0        /* SAMP */
#define ALIEN_BEAM                       1        /* SAMP */
#define BHB_CLOSE                        2        /* SAMP */
#define BHB_LOOP                         3        /* SAMP */
#define BHB_OPEN                         4        /* SAMP */
#define BHB_SHELLOPEN                    5        /* SAMP */
#define BHB_SMASH                        6        /* SAMP */
#define BURNING                          7        /* SAMP */
#define CAVESPIKE_SHAKE                  8        /* SAMP */
#define CAVESPIKE_SHATTER                9        /* SAMP */
#define CHALLENGE_READY                  10       /* SAMP */
#define CHALLENGE_WIN                    11       /* SAMP */
#define DEATHSHEAD_EXPLODE               12       /* SAMP */
#define DEATHSHEADCHILD_EXPLODE          13       /* SAMP */
#define DRILLING                         14       /* SAMP */
#define EASTEREGG_1                      15       /* SAMP */
#define EASTEREGG_2                      16       /* SAMP */
#define EASTEREGG_3                      17       /* SAMP */
#define EXPLODE_BIG                      18       /* SAMP */
#define EXPLODE_CANISTER                 19       /* SAMP */
#define EXPLODE_EMPMISSILE               20       /* SAMP */
#define EXPLODE_FIREBALL                 21       /* SAMP */
#define EXPLODE_FIRESTARTER              22       /* SAMP */
#define EXPLODE_FLAK                     23       /* SAMP */
#define EXPLODE_FUNKYNUKE                24       /* SAMP */
#define EXPLODE_HEATWAVE                 25       /* SAMP */
#define EXPLODE_LAVA                     26       /* SAMP */
#define EXPLODE_LEADSHELL                27       /* SAMP */
#define EXPLODE_MEDIUM1                  28       /* SAMP */
#define EXPLODE_MEDIUM2                  29       /* SAMP */
#define EXPLODE_MEDIUM3                  30       /* SAMP */
#define EXPLODE_MOONSHOT                 31       /* SAMP */
#define EXPLODE_MORTAR                   32       /* SAMP */
#define EXPLODE_PHOTON                   33       /* SAMP */
#define EXPLODE_SMALL                    34       /* SAMP */
#define EXPLODE_TOWERPOD                 35       /* SAMP */
#define EXPLODE_URANIUMSHELL             36       /* SAMP */
#define FIRETOAD_BOUNCE                  37       /* SAMP */
#define IONBATTERY_FIRE                  38       /* SAMP */
#define LAVA_FIRE                        39       /* SAMP */
#define LAVASHOOT_FIRE                   40       /* SAMP */
#define METALHIT1                        41       /* SAMP */
#define METALHIT2                        42       /* SAMP */
#define METALHIT3                        43       /* SAMP */
#define MINIFIGHTER_FLYBY                44       /* SAMP */
#define MOUSE_OVER                       45       /* SAMP */
#define MOUSE_SELECT                     46       /* SAMP */
#define OBC_BEACONBEEP                   47       /* SAMP */
#define OBC_BEAMFIRE                     48       /* SAMP */
#define OBC_BEAMREV                      49       /* SAMP */
#define OBC_SATFIRE                      50       /* SAMP */
#define OBC_SATREV                       51       /* SAMP */
#define POLARIS_BEEP                     52       /* SAMP */
#define POLARIS_DETONATE                 53       /* SAMP */
#define POLARIS_EMP                      54       /* SAMP */
#define POLARIS_ICESHATTER               55       /* SAMP */
#define POLARIS_MIST                     56       /* SAMP */
#define POLARIS_OPEN                     57       /* SAMP */
#define ROF_FIREBURN                     58       /* SAMP */
#define SECRET_CHAR_SWITCH               59       /* SAMP */
#define SENTRYPOD_EMP                    60       /* SAMP */
#define SENTRYPOD_OPEN                   61       /* SAMP */
#define SHIELD_BALLISTIC_POWERDOWN       62       /* SAMP */
#define SHIELD_BALLISTIC_POWERUP         63       /* SAMP */
#define SHIELD_ENERGY_POWERDOWN          64       /* SAMP */
#define SHIELD_ENERGY_POWERUP            65       /* SAMP */
#define SHIELD_HEAT_POWERDOWN            66       /* SAMP */
#define SHIELD_HEAT_POWERUP              67       /* SAMP */
#define SHIELD_NIVBUILD                  68       /* SAMP */
#define SHIELD_NIVREADY                  69       /* SAMP */
#define SHIELD_SUPERCONVENTIONALPOWERDOWN 70       /* SAMP */
#define SHIELD_SUPERCONVENTIONALPOWERUP  71       /* SAMP */
#define SHIELDHIT                        72       /* SAMP */
#define SHOT_RIC1                        73       /* SAMP */
#define SHOT_RIC2                        74       /* SAMP */
#define SHOTGUN_FIRE                     75       /* SAMP */
#define SHOTGUN_READY                    76       /* SAMP */
#define TANK_BATTERYCHARGEUP             77       /* SAMP */
#define TANK_ELECTRICCURRENT             78       /* SAMP */
#define TANK_ELECTRICLASERFIRE           79       /* SAMP */
#define TANK_EXPLODE                     80       /* SAMP */
#define TANK_FALLDAMAGE                  81       /* SAMP */
#define TANK_FIREBIG                     82       /* SAMP */
#define TANK_FIREDEATHSHEAD              83       /* SAMP */
#define TANK_FIREFIREFLY                 84       /* SAMP */
#define TANK_FIREHEATCANNON              85       /* SAMP */
#define TANK_FIREHEATRAY                 86       /* SAMP */
#define TANK_FIRELASER                   87       /* SAMP */
#define TANK_FIREMACHINEGUN              88       /* SAMP */
#define TANK_FIREMOLTENROD               89       /* SAMP */
#define TANK_FIREMOONSHOT                90       /* SAMP */
#define TANK_FIREMORTAR                  91       /* SAMP */
#define TANK_FIREPHOTON                  92       /* SAMP */
#define TANK_FIRERAILGUN                 93       /* SAMP */
#define TANK_FIRESMALL                   94       /* SAMP */
#define TANK_FIRESUPERRAIL               95       /* SAMP */
#define TANK_FIREUZI                     96       /* SAMP */
#define TANK_FLAMETHROWER                97       /* SAMP */
#define TANK_HEAVYEXPLODE1               98       /* SAMP */
#define TANK_HEAVYEXPLODE2               99       /* SAMP */
#define TANK_LASERBLAST                  100      /* SAMP */
#define TANK_LASERBLAST_REV              101      /* SAMP */
#define TANK_PIFT                        102      /* SAMP */
#define TANK_SHIELDPOWERDOWN             103      /* SAMP */
#define TANK_SHIELDPOWERUP               104      /* SAMP */
#define TANK_STARTHEATRAY                105      /* SAMP */
#define TANKTURN_ALERT                   106      /* SAMP */
#define TEL_LIGHTNING                    107      /* SAMP */
#define TEL_THUNDER                      108      /* SAMP */
#define THUNDERHIT_1                     109      /* SAMP */
#define THUNDERHIT_2                     110      /* SAMP */
#define THUNDERRUMBLE_1                  111      /* SAMP */
#define THUNDERRUMBLE_2                  112      /* SAMP */
#define TOWERPOD_BUILD                   113      /* SAMP */
#define WOLFHOWL                         114      /* SAMP */

