/* Allegro datafile object indexes, produced by grabber v4.0.3, MSVC */
/* Datafile: f:\software\CDsrc\run\data\sprites.dat */
/* Date: Fri Dec 08 11:02:17 2006 */
/* Do not hand edit! */

#define ALIENBEAM_1                      0        /* BMP  */
#define ALIENBEAM_2                      1        /* BMP  */
#define ALIENBEAM_3                      2        /* BMP  */
#define ALIENBEAM_4                      3        /* BMP  */
#define ALIENBEAMPARTICLE                4        /* BMP  */
#define ALIENBEAMUP_1                    5        /* BMP  */
#define ALIENBEAMUP_2                    6        /* BMP  */
#define ANI_OBC1                         7        /* BMP  */
#define ANI_OBC10                        8        /* BMP  */
#define ANI_OBC11                        9        /* BMP  */
#define ANI_OBC12                        10       /* BMP  */
#define ANI_OBC13                        11       /* BMP  */
#define ANI_OBC14                        12       /* BMP  */
#define ANI_OBC15                        13       /* BMP  */
#define ANI_OBC16                        14       /* BMP  */
#define ANI_OBC17                        15       /* BMP  */
#define ANI_OBC18                        16       /* BMP  */
#define ANI_OBC2                         17       /* BMP  */
#define ANI_OBC3                         18       /* BMP  */
#define ANI_OBC4                         19       /* BMP  */
#define ANI_OBC5                         20       /* BMP  */
#define ANI_OBC6                         21       /* BMP  */
#define ANI_OBC7                         22       /* BMP  */
#define ANI_OBC8                         23       /* BMP  */
#define ANI_OBC9                         24       /* BMP  */
#define BUBBLE_LARGE                     25       /* BMP  */
#define BUBBLE_MEDIUM                    26       /* BMP  */
#define BUBBLE_SMALL                     27       /* BMP  */
#define CAVESPIKE_1                      28       /* BMP  */
#define CAVESPIKE_2                      29       /* BMP  */
#define CAVESPIKE_3                      30       /* BMP  */
#define CAVESPIKE_4                      31       /* BMP  */
#define CAVESPIKE_5                      32       /* BMP  */
#define CAVESPIKESHARD1                  33       /* BMP  */
#define CAVESPIKESHARD2                  34       /* BMP  */
#define CAVESPIKESHARD3                  35       /* BMP  */
#define CAVESPIKESHARD4                  36       /* BMP  */
#define CAVESPIKESHARD5                  37       /* BMP  */
#define CAVESPIKESHARD6                  38       /* BMP  */
#define CHERRYBLOSS_1                    39       /* BMP  */
#define CHERRYBLOSS_2                    40       /* BMP  */
#define CHERRYBLOSS_3                    41       /* BMP  */
#define CHEST_DOLLAR                     42       /* BMP  */
#define CHEST_DOLLAR2                    43       /* BMP  */
#define CHEST_HEALTH                     44       /* BMP  */
#define CHEST_HEALTHSHIELD               45       /* BMP  */
#define CHEST_SHIELD                     46       /* BMP  */
#define CHEST_SUPERWEAPON                47       /* BMP  */
#define CHEST_WEAPON                     48       /* BMP  */
#define ELECTRIC_ARC1                    49       /* BMP  */
#define ELECTRIC_ARC2                    50       /* BMP  */
#define EMPTYSHELL                       51       /* BMP  */
#define EXPLODE_A1                       52       /* BMP  */
#define EXPLODE_A2                       53       /* BMP  */
#define EXPLODE_A3                       54       /* BMP  */
#define EXPLODE_A4                       55       /* BMP  */
#define EXPLODE_A5                       56       /* BMP  */
#define EXPLODE_A6                       57       /* BMP  */
#define EXPLODE_A7                       58       /* BMP  */
#define EXPLODE_A8                       59       /* BMP  */
#define EXPLODE_B1                       60       /* BMP  */
#define EXPLODE_B2                       61       /* BMP  */
#define EXPLODE_B3                       62       /* BMP  */
#define EXPLODE_B4                       63       /* BMP  */
#define EXPLODE_B5                       64       /* BMP  */
#define EXPLODE_B6                       65       /* BMP  */
#define EXPLODE_B7                       66       /* BMP  */
#define EXPLODE_B8                       67       /* BMP  */
#define EXPLODE_C1                       68       /* BMP  */
#define EXPLODE_C2                       69       /* BMP  */
#define EXPLODE_C3                       70       /* BMP  */
#define EXPLODE_C4                       71       /* BMP  */
#define EXPLODE_C5                       72       /* BMP  */
#define EXPLODE_C6                       73       /* BMP  */
#define EXPLODE_C7                       74       /* BMP  */
#define EXPLODE_C8                       75       /* BMP  */
#define FLAME_BIG                        76       /* BMP  */
#define FLAME_MEDIUM                     77       /* BMP  */
#define FLAME_SMALL                      78       /* BMP  */
#define FUELCYLINDER                     79       /* BMP  */
#define HEATCORONA                       80       /* BMP  */
#define HEATWAVE_LARGE                   81       /* BMP  */
#define HEATWAVE_MEDIUM                  82       /* BMP  */
#define HEATWAVE_SMALL                   83       /* BMP  */
#define HEATWAVE_VERYSMALL               84       /* BMP  */
#define HEATWAVE_XLARGE                  85       /* BMP  */
#define ICEBLOCK                         86       /* BMP  */
#define ICESHARD_B                       87       /* BMP  */
#define ICESHARD_BLEFT                   88       /* BMP  */
#define ICESHARD_BRIGHT                  89       /* BMP  */
#define ICESHARD_T                       90       /* BMP  */
#define ICESHARD_TLEFT                   91       /* BMP  */
#define ICESHARD_TRIGHT                  92       /* BMP  */
#define ICESPIKE1                        93       /* BMP  */
#define ICESPIKE1_1                      94       /* BMP  */
#define ICESPIKE1_2                      95       /* BMP  */
#define ICESPIKE1_3                      96       /* BMP  */
#define ICESPIKE1_4                      97       /* BMP  */
#define ICESPIKE2                        98       /* BMP  */
#define ICESPIKE2_1                      99       /* BMP  */
#define ICESPIKE2_2                      100      /* BMP  */
#define ICESPIKE2_3                      101      /* BMP  */
#define ICESPIKE2_4                      102      /* BMP  */
#define ICESPIKE3                        103      /* BMP  */
#define ICESPIKE3_1                      104      /* BMP  */
#define ICESPIKE3_2                      105      /* BMP  */
#define LIGHTNINGROD_HELLSTRIKE          106      /* BMP  */
#define LIGHTNINGROD_HSDAMAGE            107      /* BMP  */
#define LIGHTNINGROD_LIGHTNING           108      /* BMP  */
#define MAGCLOSED                        109      /* BMP  */
#define MAGOPEN1                         110      /* BMP  */
#define MAGOPEN2                         111      /* BMP  */
#define MAGOPEN3                         112      /* BMP  */
#define MAGOPEN4                         113      /* BMP  */
#define MAGOPEN5                         114      /* BMP  */
#define MAGOPEN6                         115      /* BMP  */
#define MAGPULSE1                        116      /* BMP  */
#define MAGPULSE2                        117      /* BMP  */
#define MAGPULSE3                        118      /* BMP  */
#define MAGPULSE4                        119      /* BMP  */
#define MORTARBARREL1                    120      /* BMP  */
#define MORTARBARREL2                    121      /* BMP  */
#define MORTARBASE                       122      /* BMP  */
#define NITROGENPUFF_LARGE               123      /* BMP  */
#define NITROGENPUFF_MEDIUM              124      /* BMP  */
#define P_ACIDCANISTER                   125      /* BMP  */
#define P_AS_AIRSHIP                     126      /* BMP  */
#define P_AS_FIGHTER                     127      /* BMP  */
#define P_AS_FIREBURST1                  128      /* BMP  */
#define P_AS_FIREBURST2                  129      /* BMP  */
#define P_AS_FLARE                       130      /* BMP  */
#define P_AS_FLARESMOKE                  131      /* BMP  */
#define P_AS_HEATGUN                     132      /* BMP  */
#define P_AS_TANKBAY                     133      /* BMP  */
#define P_BABYMISSILE                    134      /* BMP  */
#define P_BABYNUKE                       135      /* BMP  */
#define P_BHBOMB                         136      /* BMP  */
#define P_BHBOMB_BLOB1                   137      /* BMP  */
#define P_BHBOMB_BLOB2                   138      /* BMP  */
#define P_BHBOMB_BLOB3                   139      /* BMP  */
#define P_BHBOMB_BLOB4                   140      /* BMP  */
#define P_BHBOMB_CLOUDS                  141      /* BMP  */
#define P_BHBOMB_MATTER1                 142      /* BMP  */
#define P_BHBOMB_MATTER2                 143      /* BMP  */
#define P_BHBOMB_OPEN1                   144      /* BMP  */
#define P_BHBOMB_OPEN2                   145      /* BMP  */
#define P_BLACKMISSILE_1                 146      /* BMP  */
#define P_BLACKMISSILE_2                 147      /* BMP  */
#define P_BLUEMISSILE_1                  148      /* BMP  */
#define P_BLUEMISSILE_2                  149      /* BMP  */
#define P_BSENTRY1                       150      /* BMP  */
#define P_BSENTRY2                       151      /* BMP  */
#define P_BSENTRY3                       152      /* BMP  */
#define P_BSENTRY4                       153      /* BMP  */
#define P_BSENTRY5                       154      /* BMP  */
#define P_DEATHSHEADCHILD                155      /* BMP  */
#define P_DEATHSHEADEMPTY_1              156      /* BMP  */
#define P_DEATHSHEADEMPTY_2              157      /* BMP  */
#define P_DEATHSHEADFULL_1               158      /* BMP  */
#define P_DEATHSHEADFULL_2               159      /* BMP  */
#define P_DRILL                          160      /* BMP  */
#define P_EMPEXPLODE_TRANS               161      /* BMP  */
#define P_EMPMISSILE_1                   162      /* BMP  */
#define P_EMPMISSILE_2                   163      /* BMP  */
#define P_ESENTRY1                       164      /* BMP  */
#define P_ESENTRY2                       165      /* BMP  */
#define P_ESENTRY3                       166      /* BMP  */
#define P_ESENTRY4                       167      /* BMP  */
#define P_ESENTRY5                       168      /* BMP  */
#define P_ESENTRY_SHOT                   169      /* BMP  */
#define P_FATBOY_1                       170      /* BMP  */
#define P_FATBOY_2                       171      /* BMP  */
#define P_FIREBALL                       172      /* BMP  */
#define P_FIREFLY                        173      /* BMP  */
#define P_FIREFLY_EFFECT                 174      /* BMP  */
#define P_FIRESTARTER                    175      /* BMP  */
#define P_FIRESTARTER_F1                 176      /* BMP  */
#define P_FIRESTARTER_F2                 177      /* BMP  */
#define P_FIRESTARTER_F3                 178      /* BMP  */
#define P_FIRESTARTER_F4                 179      /* BMP  */
#define P_FIRETOAD                       180      /* BMP  */
#define P_FIRETOAD_COMPRESSED            181      /* BMP  */
#define P_FLAKSHARD_1                    182      /* BMP  */
#define P_FLAKSHARD_2                    183      /* BMP  */
#define P_FLAKSHELL                      184      /* BMP  */
#define P_FUNKYBOMB                      185      /* BMP  */
#define P_FUNKYNUKE                      186      /* BMP  */
#define P_GIGANUKE                       187      /* BMP  */
#define P_GREENLASER_PULSE               188      /* BMP  */
#define P_GREENLASER_PULSE_DIE1          189      /* BMP  */
#define P_GREENLASER_PULSE_DIE2          190      /* BMP  */
#define P_GREENLASER_PULSE_DIE3          191      /* BMP  */
#define P_GREENLASER_PULSE_DIE4          192      /* BMP  */
#define P_GREENLASER_PULSE_DIE5          193      /* BMP  */
#define P_GREENLASER_PULSE_DIE6          194      /* BMP  */
#define P_HEATRAY1                       195      /* BMP  */
#define P_HEATRAY2                       196      /* BMP  */
#define P_HEATRAY_EFFECT                 197      /* BMP  */
#define P_HEATRAY_START1                 198      /* BMP  */
#define P_HEATRAY_START2                 199      /* BMP  */
#define P_HEATWAVE                       200      /* BMP  */
#define P_HSENTRY1                       201      /* BMP  */
#define P_HSENTRY2                       202      /* BMP  */
#define P_HSENTRY3                       203      /* BMP  */
#define P_HSENTRY4                       204      /* BMP  */
#define P_HSENTRY5                       205      /* BMP  */
#define P_HSENTRY_SHOT                   206      /* BMP  */
#define P_IONBATTERY                     207      /* BMP  */
#define P_IONBATTERY_FLARE1              208      /* BMP  */
#define P_IONBATTERY_FLARE2              209      /* BMP  */
#define P_IONCANNON1                     210      /* BMP  */
#define P_IONCANNON2                     211      /* BMP  */
#define P_IONCANNON_CHARGE1              212      /* BMP  */
#define P_IONCANNON_CHARGE2              213      /* BMP  */
#define P_IONCANNON_CHARGE3              214      /* BMP  */
#define P_IONCANNON_CHARGE4              215      /* BMP  */
#define P_IONCANNON_CHARGE5              216      /* BMP  */
#define P_IONCANNON_DIE1                 217      /* BMP  */
#define P_IONCANNON_DIE2                 218      /* BMP  */
#define P_IONCANNON_DIE3                 219      /* BMP  */
#define P_IONCANNON_DIE4                 220      /* BMP  */
#define P_IONCANNON_DIE5                 221      /* BMP  */
#define P_IONCANNON_FIRE1                222      /* BMP  */
#define P_IONCANNON_FIRE2                223      /* BMP  */
#define P_IRONBALL                       224      /* BMP  */
#define P_LARGESPARKBALL1                225      /* BMP  */
#define P_LARGESPARKBALL2                226      /* BMP  */
#define P_LARGESPARKBALL3                227      /* BMP  */
#define P_LAVAROCKBIG                    228      /* BMP  */
#define P_LAVAROCKBIG_EFFECT             229      /* BMP  */
#define P_LAVAROCKSMALL                  230      /* BMP  */
#define P_LAVAROCKSMALL_EFFECT           231      /* BMP  */
#define P_LIGHTNINGROD_1                 232      /* BMP  */
#define P_MACHINEGUN_TRACER              233      /* BMP  */
#define P_MIRV_CHILD                     234      /* BMP  */
#define P_MIRV_PARENT1                   235      /* BMP  */
#define P_MIRV_PARENT2                   236      /* BMP  */
#define P_MISSILE_1                      237      /* BMP  */
#define P_MISSILE_2                      238      /* BMP  */
#define P_MORTARSHELL                    239      /* BMP  */
#define P_NAPALMCANISTER                 240      /* BMP  */
#define P_NEEDLE1                        241      /* BMP  */
#define P_NEEDLE2                        242      /* BMP  */
#define P_NUKE                           243      /* BMP  */
#define P_OBCBEACON1                     244      /* BMP  */
#define P_OBCBEACON2                     245      /* BMP  */
#define P_OBCFLAMEBURN1                  246      /* BMP  */
#define P_OBCFULLBEAM1                   247      /* BMP  */
#define P_OBCFULLBEAM2                   248      /* BMP  */
#define P_OBCIONFLAME1                   249      /* BMP  */
#define P_OBCIONFLAME2                   250      /* BMP  */
#define P_OBCIONFLAME3                   251      /* BMP  */
#define P_OBCMEDIUMBEAM                  252      /* BMP  */
#define P_OBCTHINBEAM1                   253      /* BMP  */
#define P_OBCTHINBEAM2                   254      /* BMP  */
#define P_PLASMACANISTER                 255      /* BMP  */
#define P_POLARISEMPBLAST                256      /* BMP  */
#define P_POLARISLAND1                   257      /* BMP  */
#define P_POLARISLAND2                   258      /* BMP  */
#define P_POLARISLAND3                   259      /* BMP  */
#define P_POLARISMISSILE1                260      /* BMP  */
#define P_POLARISMISSILE2                261      /* BMP  */
#define P_PROTON                         262      /* BMP  */
#define P_RAILGUNSMOKE                   263      /* BMP  */
#define P_ROF_FLAME1                     264      /* BMP  */
#define P_ROF_FLAME2                     265      /* BMP  */
#define P_ROF_FLAME3                     266      /* BMP  */
#define P_ROF_OPEN1                      267      /* BMP  */
#define P_ROF_OPEN2                      268      /* BMP  */
#define P_ROF_OPEN3                      269      /* BMP  */
#define P_ROF_PROJECTILE                 270      /* BMP  */
#define P_ROLLER                         271      /* BMP  */
#define P_SB_FULLMOON                    272      /* BMP  */
#define P_SB_MOONSHOT                    273      /* BMP  */
#define P_SB_PROJECTILE                  274      /* BMP  */
#define P_SHELL                          275      /* BMP  */
#define P_SPARKBALL1                     276      /* BMP  */
#define P_SPARKBALL2                     277      /* BMP  */
#define P_SPIKEDBALL                     278      /* BMP  */
#define P_SUPERRAILSMOKE1                279      /* BMP  */
#define P_SUPERRAILSMOKE2                280      /* BMP  */
#define P_SUPERRAILSMOKE3                281      /* BMP  */
#define P_SUPERRAILSMOKE4                282      /* BMP  */
#define P_SUPERRAILSMOKE5                283      /* BMP  */
#define P_SUPERRAILSMOKE6                284      /* BMP  */
#define P_TEL_NEGATIVE                   285      /* BMP  */
#define P_TEL_POSITIVE                   286      /* BMP  */
#define P_TOWERPOD1                      287      /* BMP  */
#define P_TOWERPOD2                      288      /* BMP  */
#define P_TOWERPOD_BUILD1                289      /* BMP  */
#define P_TOWERPOD_BUILD10               290      /* BMP  */
#define P_TOWERPOD_BUILD11               291      /* BMP  */
#define P_TOWERPOD_BUILD2                292      /* BMP  */
#define P_TOWERPOD_BUILD3                293      /* BMP  */
#define P_TOWERPOD_BUILD4                294      /* BMP  */
#define P_TOWERPOD_BUILD5                295      /* BMP  */
#define P_TOWERPOD_BUILD6                296      /* BMP  */
#define P_TOWERPOD_BUILD7                297      /* BMP  */
#define P_TOWERPOD_BUILD8                298      /* BMP  */
#define P_TOWERPOD_BUILD9                299      /* BMP  */
#define P_URANIUMSHELL                   300      /* BMP  */
#define P_WATERCANISTER                  301      /* BMP  */
#define RAINDROP                         302      /* BMP  */
#define SHIELD_BALLISTIC_1               303      /* BMP  */
#define SHIELD_BALLISTIC_2               304      /* BMP  */
#define SHIELD_BALLISTIC_3               305      /* BMP  */
#define SHIELD_BALLISTIC_4               306      /* BMP  */
#define SHIELD_BALLISTIC_5               307      /* BMP  */
#define SHIELD_BALLISTIC_6               308      /* BMP  */
#define SHIELD_CONVENTIONAL              309      /* BMP  */
#define SHIELD_ELECTRIC_1                310      /* BMP  */
#define SHIELD_ELECTRIC_2                311      /* BMP  */
#define SHIELD_ELECTRIC_3                312      /* BMP  */
#define SHIELD_ELECTRIC_4                313      /* BMP  */
#define SHIELD_ELECTRIC_5                314      /* BMP  */
#define SHIELD_ELECTRIC_6                315      /* BMP  */
#define SHIELD_FIRE_1                    316      /* BMP  */
#define SHIELD_FIRE_2                    317      /* BMP  */
#define SHIELD_FIRE_3                    318      /* BMP  */
#define SHIELD_FIRE_4                    319      /* BMP  */
#define SHIELD_FIRE_5                    320      /* BMP  */
#define SHIELD_NIV_1                     321      /* BMP  */
#define SHIELD_NIV_2                     322      /* BMP  */
#define SHIELD_NIV_3                     323      /* BMP  */
#define SHIELD_NIV_4                     324      /* BMP  */
#define SHIELD_NIV_B1                    325      /* BMP  */
#define SHIELD_NIV_B2                    326      /* BMP  */
#define SHIELD_NIV_B3                    327      /* BMP  */
#define SHIELD_NIV_B4                    328      /* BMP  */
#define SHIELD_NIV_B5                    329      /* BMP  */
#define SHIELD_SUPERCONVENTIONAL         330      /* BMP  */
#define SMALLEXPLODE_A1                  331      /* BMP  */
#define SMALLEXPLODE_A2                  332      /* BMP  */
#define SMALLEXPLODE_A3                  333      /* BMP  */
#define SMALLEXPLODE_A4                  334      /* BMP  */
#define SMALLEXPLODE_A5                  335      /* BMP  */
#define SMALLEXPLODE_A6                  336      /* BMP  */
#define SMALLEXPLODE_A7                  337      /* BMP  */
#define SMALLEXPLODE_A8                  338      /* BMP  */
#define SMALLEXPLODE_B1                  339      /* BMP  */
#define SMALLEXPLODE_B2                  340      /* BMP  */
#define SMALLEXPLODE_B3                  341      /* BMP  */
#define SMALLEXPLODE_B4                  342      /* BMP  */
#define SMALLEXPLODE_B5                  343      /* BMP  */
#define SMALLEXPLODE_B6                  344      /* BMP  */
#define SMOKE_BLACK_LARGE                345      /* BMP  */
#define SMOKE_BLACK_MEDIUM               346      /* BMP  */
#define SMOKE_BLACK_SMALL                347      /* BMP  */
#define SMOKE_BLACK_XLARGE               348      /* BMP  */
#define SMOKE_GRAY_LARGE                 349      /* BMP  */
#define SMOKE_GRAY_MEDIUM                350      /* BMP  */
#define SMOKE_GRAY_SMALL                 351      /* BMP  */
#define SMOKE_GRAY_XLARGE                352      /* BMP  */
#define SNOWFLAKE_LARGE                  353      /* BMP  */
#define SNOWFLAKE_MEDIUM                 354      /* BMP  */
#define SNOWFLAKE_SMALL                  355      /* BMP  */
#define TANK_MUZZLEFLARE                 356      /* BMP  */
#define TANK_PHOTONFLARE                 357      /* BMP  */
#define TANKGIB_1                        358      /* BMP  */
#define TANKGIB_2                        359      /* BMP  */
#define TANKGIB_3                        360      /* BMP  */
#define TANKGIB_4                        361      /* BMP  */
#define TANKGIB_5                        362      /* BMP  */
#define TREASURECLOSED                   363      /* BMP  */
#define TREASUREOPEN                     364      /* BMP  */
#define TURNARROW                        365      /* BMP  */
#define WATER_SPLASH1                    366      /* BMP  */
#define WATER_SPLASH2                    367      /* BMP  */
#define WATER_SPLASH3                    368      /* BMP  */
#define WATER_SPLASH4                    369      /* BMP  */

